name: Deploy ES³ SML Documentation to GitHub Pages

on:
  push:
    branches:
      - main # Generate DOcumaentation from main
      - UpdateDocs # Only for Testing

# Set permissions for deployment on GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one parallel deployment process only
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/mkdocs.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install MkDocs & Material Theme
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install mkdocs-material

      - name: Download and install stlite-mountable dependency
        run: |
          # Erstellt das Zielverzeichnis im docs-Ordner
          mkdir -p docs/stlite
          
          # Lädt die offizielle Tarball-Dependency von npm herunter
          curl -L https://registry.npmjs.org/@stlite/mountable/-/mountable-0.59.0.tgz -o mountable.tgz
          
          # Entpackt die Quelldateien
          tar -xzf mountable.tgz
          
          # Kopiert den gesamten Build (inkl. aller Worker und Chunks) in Ihre Dokumentation
          cp -r package/build/* docs/stlite/
          
          # Räumt temporäre Dateien auf
          rm -rf package mountable.tgz
          
      - name: Build MkDocs Site
        run: mkdocs build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "site" # Standard Outpit Folder of MkDocs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
